// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RideDispatch.Infrastructure.Persistence;

#nullable disable

namespace RideDispatch.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DispatchDbContext))]
    [Migration("20261009034442_AddAllocationCandidateEvaluations")]
    partial class AddAllocationCandidateEvaluations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RideDispatch.Domain.Dispatch.AllocationCandidateEvaluation", b =>
                {
                    b.Property<Guid>("AllocationRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("allocation_run_id");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<DateTimeOffset?>("AvailableSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_since");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_meters");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_eligible");

                    b.Property<DateTimeOffset>("LocationRecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("location_recorded_at");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.HasKey("AllocationRunId", "DriverId");

                    b.HasIndex("DriverId");

                    b.ToTable("allocation_candidate_evaluations", null, t =>
                        {
                            t.HasCheckConstraint("ck_allocation_candidate_evaluations_rank", "(is_eligible AND rank IS NOT NULL AND rank > 0) OR (NOT is_eligible AND rank IS NULL)");
                        });
                });

            modelBuilder.Entity("RideDispatch.Domain.Dispatch.AllocationCandidateRejection", b =>
                {
                    b.Property<Guid>("AllocationRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("allocation_run_id");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reason");

                    b.HasKey("AllocationRunId", "DriverId", "Reason");

                    b.ToTable("allocation_candidate_rejections", (string)null);
                });

            modelBuilder.Entity("RideDispatch.Domain.Dispatch.AllocationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("RankingPolicy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ranking_policy");

                    b.Property<Guid?>("RecommendedDriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("recommended_driver_id");

                    b.Property<Guid>("RideRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("ride_request_id");

                    b.HasKey("Id");

                    b.HasIndex("RecommendedDriverId");

                    b.HasIndex("RideRequestId");

                    b.ToTable("allocation_runs", (string)null);
                });

            modelBuilder.Entity("RideDispatch.Domain.Drivers.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("approval_status");

                    b.Property<DateTimeOffset?>("AvailableSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_since");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("OperationalStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("operational_status");

                    b.HasKey("Id");

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("RideDispatch.Domain.Passengers.Passenger", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.ToTable("passengers", (string)null);
                });

            modelBuilder.Entity("RideDispatch.Domain.RideRequests.RideRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BookingSource")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("booking_source");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_name");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("DestinationLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("destination_latitude");

                    b.Property<double>("DestinationLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("destination_longitude");

                    b.Property<int>("EstimatedTripDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_trip_duration_seconds");

                    b.Property<Guid?>("PassengerId")
                        .HasColumnType("uuid")
                        .HasColumnName("passenger_id");

                    b.Property<double>("PickupLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("pickup_latitude");

                    b.Property<double>("PickupLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("pickup_longitude");

                    b.Property<DateTimeOffset?>("RequestedPickupAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_pickup_at");

                    b.Property<string>("RequiredVehicleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("required_vehicle_type");

                    b.Property<string>("Timing")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("timing");

                    b.HasKey("Id");

                    b.HasIndex("PassengerId");

                    b.ToTable("ride_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_ride_requests_estimated_trip_duration_positive", "estimated_trip_duration_seconds > 0");

                            t.HasCheckConstraint("ck_ride_requests_timing_requested_pickup_consistency", "(timing = 'Immediate' AND requested_pickup_at IS NULL) OR (timing = 'Scheduled' AND requested_pickup_at IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("RideDispatch.Domain.Vehicles.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("plate_number");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("DriverId")
                        .IsUnique();

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("RideDispatch.Infrastructure.Persistence.Models.DriverFinancialStandingRecord", b =>
                {
                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<decimal>("CommissionBalance")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("commission_balance");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("DriverId");

                    b.ToTable("driver_financial_standings", null, t =>
                        {
                            t.HasCheckConstraint("ck_driver_financial_standings_commission_balance_nonnegative", "commission_balance >= 0");
                        });
                });

            modelBuilder.Entity("RideDispatch.Infrastructure.Persistence.Models.DriverLocationRecord", b =>
                {
                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<Point>("Position")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("position");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.HasKey("DriverId");

                    b.HasIndex("Position");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Position"), "gist");

                    b.ToTable("driver_locations", (string)null);
                });

            modelBuilder.Entity("RideDispatch.Domain.Dispatch.AllocationCandidateEvaluation", b =>
                {
                    b.HasOne("RideDispatch.Domain.Dispatch.AllocationRun", null)
                        .WithMany("CandidateEvaluations")
                        .HasForeignKey("AllocationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RideDispatch.Domain.Drivers.Driver", null)
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RideDispatch.Domain.Dispatch.AllocationCandidateRejection", b =>
                {
                    b.HasOne("RideDispatch.Domain.Dispatch.AllocationCandidateEvaluation", null)
                        .WithMany("Rejections")
                        .HasForeignKey("AllocationRunId", "DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RideDispatch.Domain.Dispatch.AllocationRun", b =>
                {
                    b.HasOne("RideDispatch.Domain.Drivers.Driver", null)
                        .WithMany()
                        .HasForeignKey("RecommendedDriverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RideDispatch.Domain.RideRequests.RideRequest", null)
                        .WithMany()
                        .HasForeignKey("RideRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RideDispatch.Domain.RideRequests.RideRequest", b =>
                {
                    b.HasOne("RideDispatch.Domain.Passengers.Passenger", null)
                        .WithMany()
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RideDispatch.Domain.Vehicles.Vehicle", b =>
                {
                    b.HasOne("RideDispatch.Domain.Drivers.Driver", null)
                        .WithOne()
                        .HasForeignKey("RideDispatch.Domain.Vehicles.Vehicle", "DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RideDispatch.Infrastructure.Persistence.Models.DriverFinancialStandingRecord", b =>
                {
                    b.HasOne("RideDispatch.Domain.Drivers.Driver", null)
                        .WithOne()
                        .HasForeignKey("RideDispatch.Infrastructure.Persistence.Models.DriverFinancialStandingRecord", "DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RideDispatch.Infrastructure.Persistence.Models.DriverLocationRecord", b =>
                {
                    b.HasOne("RideDispatch.Domain.Drivers.Driver", null)
                        .WithOne()
                        .HasForeignKey("RideDispatch.Infrastructure.Persistence.Models.DriverLocationRecord", "DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RideDispatch.Domain.Dispatch.AllocationCandidateEvaluation", b =>
                {
                    b.Navigation("Rejections");
                });

            modelBuilder.Entity("RideDispatch.Domain.Dispatch.AllocationRun", b =>
                {
                    b.Navigation("CandidateEvaluations");
                });
#pragma warning restore 612, 618
        }
    }
}
